# Generated by Django 3.0.7 on 2020-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
